spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: back
  profiles:
    active: dev
  output:
    ansi:
      enabled: always
  datasource:
    hikari:
      auto-commit: false
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  jackson:
    serialization:
      fail-on-empty-beans: false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 100
  security:
    debug: true

jwt:
  secret: ${JWT_SECRET:back-application-jwt-secret-key-must-be-at-least-32-bytes}
  expiration: 3600000 # 1시간 (ms)
springdoc:
  default-produces-media-type: application/json;charset=UTF-8
logging:
  level:
    org.hibernate.orm.jdbc.bind: DEBUG
    org.hibernate.orm.jdbc.extract: DEBUG
    org.springframework.transaction.interceptor: DEBUG
    com.back: DEBUG
    org.springframework.security: DEBUG
