-- 레거시 스키마 보정 스크립트(수동 실행)
-- 목적:
-- 1) id 컬럼 자동 증가(IDENTITY) 누락 보정
-- 2) difficulty_rating nullable 보정(UNRATED 허용)

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'problems'
          AND column_name = 'id'
          AND is_identity = 'NO'
    ) THEN
        ALTER TABLE problems
            ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    END IF;
END $$;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'tags'
          AND column_name = 'id'
          AND is_identity = 'NO'
    ) THEN
        ALTER TABLE tags
            ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    END IF;
END $$;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'test_cases'
          AND column_name = 'id'
          AND is_identity = 'NO'
    ) THEN
        ALTER TABLE test_cases
            ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    END IF;
END $$;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = 'problem_tag_connect'
          AND column_name = 'id'
          AND is_identity = 'NO'
    ) THEN
        ALTER TABLE problem_tag_connect
            ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
    END IF;
END $$;

-- 기존 데이터가 있을 수 있으므로 시퀀스를 현재 최대 id 다음 값으로 동기화한다.
SELECT setval(
    pg_get_serial_sequence('problems', 'id'),
    COALESCE((SELECT MAX(id) FROM problems), 0) + 1,
    false
);
SELECT setval(
    pg_get_serial_sequence('tags', 'id'),
    COALESCE((SELECT MAX(id) FROM tags), 0) + 1,
    false
);
SELECT setval(
    pg_get_serial_sequence('test_cases', 'id'),
    COALESCE((SELECT MAX(id) FROM test_cases), 0) + 1,
    false
);
SELECT setval(
    pg_get_serial_sequence('problem_tag_connect', 'id'),
    COALESCE((SELECT MAX(id) FROM problem_tag_connect), 0) + 1,
    false
);

-- rating이 없는 문제(UNRATED)를 위해 NULL 허용으로 보정한다.
ALTER TABLE problems
    ALTER COLUMN difficulty_rating DROP NOT NULL;

-- 포맷 컬럼이 없으면 추가한다.
ALTER TABLE problems
    ADD COLUMN IF NOT EXISTS source_problem_id VARCHAR(50),
    ADD COLUMN IF NOT EXISTS input_format TEXT,
    ADD COLUMN IF NOT EXISTS output_format TEXT;

-- 원본 문제 식별자의 중복 입력을 방지한다(NULL은 허용).
CREATE UNIQUE INDEX IF NOT EXISTS uq_problems_source_problem_id ON problems (source_problem_id);

-- 기존 difficulty 값을 EASY/MEDIUM/HARD 3단계로 정규화한다.
UPDATE problems
SET difficulty = CASE
    WHEN difficulty_rating IS NULL OR difficulty_rating < 1400 THEN 'EASY'
    WHEN difficulty_rating < 2200 THEN 'MEDIUM'
    ELSE 'HARD'
END;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'ck_problems_difficulty'
    ) THEN
        ALTER TABLE problems
            ADD CONSTRAINT ck_problems_difficulty
            CHECK (difficulty IN ('EASY', 'MEDIUM', 'HARD'));
    END IF;
END $$;
